# Generated by Django 6.0.7 on 2026-07-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='page',
            field=models.CharField(choices=[('truck', 'Truck Menu'), ('family', 'Family Menu'), ('both', 'Both Pages')], default='both', max_length=10),
        ),
        migrations.AlterField(
            model_name='facilitybadge',
            name='emoji',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='facilitybadge',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitybadge',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
